// Personal families shipped with the app itself, present on every fresh
// install (see useSettings.js's defaultSettings) — created and tested by
// Pierre in-app, then exported and baked in here so a new device/install
// isn't missing them. Same shape as a player-built family (id, name,
// entries), just shipped instead of created via "Créer une famille perso".
// A player can still delete or edit any of these like any other personal
// family — nothing here is protected.
//
// Rebuilt 2026-08-03 after the "Entraînement ciblé" lock was restored (see
// enumeratePossibleTricks in trickGenerator.js) — the previous set was built
// while that lock was bypassed for family creation, so several entries had
// picked up a bare "270"/"450" (no AO/True direction) or an unintended
// "Switch" from a live setting unrelated to the family itself.
export const DEFAULT_CUSTOM_FAMILIES = [
  {
    "id": "custom-1785792336213",
    "name": "Backslide to AO Top",
    "entries": [
      {
        "grindName": "FS Backslide",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Makio",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Backslide",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Acid",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Backslide",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Mistrial",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Backslide",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "PStar",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Backslide",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Backslide",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "X-Grind",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Backslide",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Mizou",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Backslide",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Torque Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      }
    ]
  },
  {
    "id": "custom-1785792386060",
    "name": "BS Backslide to True",
    "entries": [
      {
        "grindName": "BS Backslide",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Acid",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Backslide",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Makio",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Backslide",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Mistrial",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Backslide",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Mizou",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Backslide",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "PStar",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Backslide",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Soul",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Backslide",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Torque Soul",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Backslide",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "X-Grind",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      }
    ]
  },
  {
    "id": "custom-1785792431180",
    "name": "FS Torque to AO",
    "entries": [
      {
        "grindName": "FS Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Acid",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Makio",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Mistrial",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Mizou",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "PStar",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Soul",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "X-Grind",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Torque Soul",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      }
    ]
  },
  {
    "id": "custom-1785792454376",
    "name": "BS Torque to True Top",
    "entries": [
      {
        "grindName": "BS Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Makio",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Mizou",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Acid",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Mistrial",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "PStar",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Torque Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "X-Grind",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      }
    ]
  },
  {
    "id": "custom-1785792516856",
    "name": "BS Full Torque to True Top",
    "entries": [
      {
        "grindName": "BS Full Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Makio",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Full Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Mizou",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Full Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Acid",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Full Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Mistrial",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Full Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "PStar",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Full Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Full Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Torque Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Full Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "X-Grind",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      }
    ]
  },
  {
    "id": "custom-1785792545818",
    "name": "FS Full Torque to AO",
    "entries": [
      {
        "grindName": "FS Full Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Acid",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Full Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Makio",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Full Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Mistrial",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Full Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Mizou",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Full Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "PStar",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Full Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Soul",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Full Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "X-Grind",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Full Torque",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Torque Soul",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      }
    ]
  },
  {
    "id": "custom-1785792576082",
    "name": "FS Royal to AO Top",
    "entries": [
      {
        "grindName": "FS Royale",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Makio",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Royale",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Acid",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Royale",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Mistrial",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Royale",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "PStar",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Royale",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Royale",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "X-Grind",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Royale",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Mizou",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Royale",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Torque Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      }
    ]
  },
  {
    "id": "custom-1785792598681",
    "name": "BS Royal to True",
    "entries": [
      {
        "grindName": "BS Royale",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Acid",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Royale",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Makio",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Royale",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Mistrial",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Royale",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Mizou",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Royale",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "PStar",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Royale",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Soul",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Royale",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Torque Soul",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Royale",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "X-Grind",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      }
    ]
  },
  {
    "id": "custom-1785792668081",
    "name": "FS Unity to AO",
    "entries": [
      {
        "grindName": "FS Unity",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Acid",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Unity",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Makio",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Unity",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Mistrial",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Unity",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Mizou",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Unity",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "PStar",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Unity",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Soul",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Unity",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "X-Grind",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Unity",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Torque Soul",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      }
    ]
  },
  {
    "id": "custom-1785792700772",
    "name": "BS Unity to True Top",
    "entries": [
      {
        "grindName": "BS Unity",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Makio",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Unity",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Mizou",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Unity",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Acid",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Unity",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Mistrial",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Unity",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "PStar",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Unity",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Unity",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Torque Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Unity",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "X-Grind",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      }
    ]
  },
  {
    "id": "custom-1785792735167",
    "name": "BS Savannah to True",
    "entries": [
      {
        "grindName": "BS Savannah",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Acid",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Savannah",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Makio",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Savannah",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Mistrial",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Savannah",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Mizou",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Savannah",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "PStar",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Savannah",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Soul",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Savannah",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Torque Soul",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Savannah",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "X-Grind",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Unity",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Acid",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Unity",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Makio",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Unity",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Mistrial",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Unity",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Mizou",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Unity",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "PStar",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Unity",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Soul",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Unity",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Torque Soul",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "BS Unity",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "X-Grind",
        "switchUpVariationName": null,
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      }
    ]
  },
  {
    "id": "custom-1785792772891",
    "name": "FS Savannah To AO Top",
    "entries": [
      {
        "grindName": "FS Savannah",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Makio",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Savannah",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Acid",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Savannah",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Mistrial",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Savannah",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "PStar",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Savannah",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Savannah",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "X-Grind",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Savannah",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Mizou",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "FS Savannah",
        "variationName": "None",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "Forwards",
        "switchUpGrindName": "Torque Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 270",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      }
    ]
  },
  {
    "id": "custom-1785792845544",
    "name": "Top To Switch True Top",
    "entries": [
      {
        "grindName": "Makio",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Makio",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Makio",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mizou",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Makio",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Acid",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Makio",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mistrial",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Makio",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "PStar",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Makio",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Makio",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Torque Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Makio",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "X-Grind",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mizou",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Makio",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mizou",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mizou",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mizou",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Acid",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mizou",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mistrial",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mizou",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "PStar",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mizou",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mizou",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Torque Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mizou",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "X-Grind",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Acid",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Makio",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Acid",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mizou",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Acid",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Acid",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Acid",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mistrial",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Acid",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "PStar",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Acid",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Acid",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Torque Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Acid",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "X-Grind",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mistrial",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Makio",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mistrial",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mizou",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mistrial",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Acid",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mistrial",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mistrial",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mistrial",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "PStar",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mistrial",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mistrial",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Torque Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mistrial",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "X-Grind",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "PStar",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Makio",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "PStar",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mizou",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "PStar",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Acid",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "PStar",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mistrial",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "PStar",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "PStar",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "PStar",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "PStar",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Torque Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "PStar",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "X-Grind",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Soul",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Makio",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Soul",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mizou",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Soul",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Acid",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Soul",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mistrial",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Soul",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "PStar",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Soul",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Soul",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Torque Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Soul",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "X-Grind",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Torque Soul",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Makio",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Torque Soul",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mizou",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Torque Soul",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Acid",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Torque Soul",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mistrial",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Torque Soul",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "PStar",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Torque Soul",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Torque Soul",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Torque Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Torque Soul",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "X-Grind",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "X-Grind",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Makio",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "X-Grind",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mizou",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "X-Grind",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Acid",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "X-Grind",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mistrial",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "X-Grind",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "PStar",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "X-Grind",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "X-Grind",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Torque Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "X-Grind",
        "variationName": "Topside",
        "approach": "Forwards",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "X-Grind",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      }
    ]
  },
  {
    "id": "custom-1785792885044",
    "name": "Switch Top to True Top",
    "entries": [
      {
        "grindName": "Makio",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Makio",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Makio",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mizou",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Makio",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Acid",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Makio",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mistrial",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Makio",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "PStar",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Makio",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Makio",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Torque Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Makio",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "X-Grind",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mizou",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Makio",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mizou",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mizou",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mizou",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Acid",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mizou",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mistrial",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mizou",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "PStar",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mizou",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mizou",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Torque Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mizou",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "X-Grind",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Acid",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Makio",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Acid",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mizou",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Acid",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Acid",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Acid",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mistrial",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Acid",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "PStar",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Acid",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Acid",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Torque Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Acid",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "X-Grind",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mistrial",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Makio",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mistrial",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mizou",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mistrial",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Acid",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mistrial",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mistrial",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mistrial",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "PStar",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mistrial",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mistrial",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Torque Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Mistrial",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "X-Grind",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "PStar",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Makio",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "PStar",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mizou",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "PStar",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Acid",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "PStar",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mistrial",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "PStar",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "PStar",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "PStar",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "PStar",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Torque Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "PStar",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "X-Grind",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Soul",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Makio",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Soul",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mizou",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Soul",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Acid",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Soul",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mistrial",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Soul",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "PStar",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Soul",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Soul",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Torque Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Soul",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "X-Grind",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Torque Soul",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Makio",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Torque Soul",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mizou",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Torque Soul",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Acid",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Torque Soul",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mistrial",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Torque Soul",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "PStar",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Torque Soul",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Torque Soul",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Torque Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "Torque Soul",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "X-Grind",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "X-Grind",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Makio",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "X-Grind",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mizou",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "X-Grind",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Acid",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "X-Grind",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Mistrial",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "X-Grind",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "PStar",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "X-Grind",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "X-Grind",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "Torque Soul",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      },
      {
        "grindName": "X-Grind",
        "variationName": "Topside",
        "approach": "Switch",
        "spinToName": "None",
        "spinOffName": "None",
        "switchUpGrindName": "X-Grind",
        "switchUpVariationName": "Topside",
        "switchSpinName": "Outspin 180",
        "switchUp2GrindName": null,
        "switchUp2VariationName": null,
        "switchSpin2Name": null
      }
    ]
  }
];